import logging
from sqlalchemy.orm import Session
from app.core.database import SessionLocal
from app.models.reference_data import Country

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Comprehensive list of countries with ISO 3166-1 alpha-2 code, name, currency code, and currency name
COUNTRIES = [
    {"code": "AF", "name": "Afghanistan", "currency_code": "AFN", "currency_name": "Afghan Afghani"},
    {"code": "AL", "name": "Albania", "currency_code": "ALL", "currency_name": "Albanian Lek"},
    {"code": "DZ", "name": "Algeria", "currency_code": "DZD", "currency_name": "Algerian Dinar"},
    {"code": "AS", "name": "American Samoa", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "AD", "name": "Andorra", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "AO", "name": "Angola", "currency_code": "AOA", "currency_name": "Angolan Kwanza"},
    {"code": "AI", "name": "Anguilla", "currency_code": "XCD", "currency_name": "East Caribbean Dollar"},
    {"code": "AQ", "name": "Antarctica", "currency_code": None, "currency_name": None},
    {"code": "AG", "name": "Antigua and Barbuda", "currency_code": "XCD", "currency_name": "East Caribbean Dollar"},
    {"code": "AR", "name": "Argentina", "currency_code": "ARS", "currency_name": "Argentine Peso"},
    {"code": "AM", "name": "Armenia", "currency_code": "AMD", "currency_name": "Armenian Dram"},
    {"code": "AW", "name": "Aruba", "currency_code": "AWG", "currency_name": "Aruban Florin"},
    {"code": "AU", "name": "Australia", "currency_code": "AUD", "currency_name": "Australian Dollar"},
    {"code": "AT", "name": "Austria", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "AZ", "name": "Azerbaijan", "currency_code": "AZN", "currency_name": "Azerbaijani Manat"},
    {"code": "BS", "name": "Bahamas", "currency_code": "BSD", "currency_name": "Bahamian Dollar"},
    {"code": "BH", "name": "Bahrain", "currency_code": "BHD", "currency_name": "Bahraini Dinar"},
    {"code": "BD", "name": "Bangladesh", "currency_code": "BDT", "currency_name": "Bangladeshi Taka"},
    {"code": "BB", "name": "Barbados", "currency_code": "BBD", "currency_name": "Barbadian Dollar"},
    {"code": "BY", "name": "Belarus", "currency_code": "BYN", "currency_name": "Belarusian Ruble"},
    {"code": "BE", "name": "Belgium", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "BZ", "name": "Belize", "currency_code": "BZD", "currency_name": "Belize Dollar"},
    {"code": "BJ", "name": "Benin", "currency_code": "XOF", "currency_name": "West African CFA Franc"},
    {"code": "BM", "name": "Bermuda", "currency_code": "BMD", "currency_name": "Bermudian Dollar"},
    {"code": "BT", "name": "Bhutan", "currency_code": "BTN", "currency_name": "Bhutanese Ngultrum"},
    {"code": "BO", "name": "Bolivia", "currency_code": "BOB", "currency_name": "Bolivian Boliviano"},
    {"code": "BA", "name": "Bosnia and Herzegovina", "currency_code": "BAM", "currency_name": "Bosnia-Herzegovina Convertible Mark"},
    {"code": "BW", "name": "Botswana", "currency_code": "BWP", "currency_name": "Botswana Pula"},
    {"code": "BV", "name": "Bouvet Island", "currency_code": "NOK", "currency_name": "Norwegian Krone"},
    {"code": "BR", "name": "Brazil", "currency_code": "BRL", "currency_name": "Brazilian Real"},
    {"code": "IO", "name": "British Indian Ocean Territory", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "BN", "name": "Brunei Darussalam", "currency_code": "BND", "currency_name": "Brunei Dollar"},
    {"code": "BG", "name": "Bulgaria", "currency_code": "BGN", "currency_name": "Bulgarian Lev"},
    {"code": "BF", "name": "Burkina Faso", "currency_code": "XOF", "currency_name": "West African CFA Franc"},
    {"code": "BI", "name": "Burundi", "currency_code": "BIF", "currency_name": "Burundian Franc"},
    {"code": "KH", "name": "Cambodia", "currency_code": "KHR", "currency_name": "Cambodian Riel"},
    {"code": "CM", "name": "Cameroon", "currency_code": "XAF", "currency_name": "Central African CFA Franc"},
    {"code": "CA", "name": "Canada", "currency_code": "CAD", "currency_name": "Canadian Dollar"},
    {"code": "CV", "name": "Cape Verde", "currency_code": "CVE", "currency_name": "Cape Verdean Escudo"},
    {"code": "KY", "name": "Cayman Islands", "currency_code": "KYD", "currency_name": "Cayman Islands Dollar"},
    {"code": "CF", "name": "Central African Republic", "currency_code": "XAF", "currency_name": "Central African CFA Franc"},
    {"code": "TD", "name": "Chad", "currency_code": "XAF", "currency_name": "Central African CFA Franc"},
    {"code": "CL", "name": "Chile", "currency_code": "CLP", "currency_name": "Chilean Peso"},
    {"code": "CN", "name": "China", "currency_code": "CNY", "currency_name": "Chinese Yuan"},
    {"code": "CX", "name": "Christmas Island", "currency_code": "AUD", "currency_name": "Australian Dollar"},
    {"code": "CC", "name": "Cocos (Keeling) Islands", "currency_code": "AUD", "currency_name": "Australian Dollar"},
    {"code": "CO", "name": "Colombia", "currency_code": "COP", "currency_name": "Colombian Peso"},
    {"code": "KM", "name": "Comoros", "currency_code": "KMF", "currency_name": "Comorian Franc"},
    {"code": "CG", "name": "Congo", "currency_code": "XAF", "currency_name": "Central African CFA Franc"},
    {"code": "CD", "name": "Congo, Democratic Republic of the", "currency_code": "CDF", "currency_name": "Congolese Franc"},
    {"code": "CK", "name": "Cook Islands", "currency_code": "NZD", "currency_name": "New Zealand Dollar"},
    {"code": "CR", "name": "Costa Rica", "currency_code": "CRC", "currency_name": "Costa Rican Colón"},
    {"code": "CI", "name": "Côte d'Ivoire", "currency_code": "XOF", "currency_name": "West African CFA Franc"},
    {"code": "HR", "name": "Croatia", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "CU", "name": "Cuba", "currency_code": "CUP", "currency_name": "Cuban Peso"},
    {"code": "CY", "name": "Cyprus", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "CZ", "name": "Czech Republic", "currency_code": "CZK", "currency_name": "Czech Koruna"},
    {"code": "DK", "name": "Denmark", "currency_code": "DKK", "currency_name": "Danish Krone"},
    {"code": "DJ", "name": "Djibouti", "currency_code": "DJF", "currency_name": "Djiboutian Franc"},
    {"code": "DM", "name": "Dominica", "currency_code": "XCD", "currency_name": "East Caribbean Dollar"},
    {"code": "DO", "name": "Dominican Republic", "currency_code": "DOP", "currency_name": "Dominican Peso"},
    {"code": "EC", "name": "Ecuador", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "EG", "name": "Egypt", "currency_code": "EGP", "currency_name": "Egyptian Pound"},
    {"code": "SV", "name": "El Salvador", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "GQ", "name": "Equatorial Guinea", "currency_code": "XAF", "currency_name": "Central African CFA Franc"},
    {"code": "ER", "name": "Eritrea", "currency_code": "ERN", "currency_name": "Eritrean Nakfa"},
    {"code": "EE", "name": "Estonia", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "ET", "name": "Ethiopia", "currency_code": "ETB", "currency_name": "Ethiopian Birr"},
    {"code": "FK", "name": "Falkland Islands (Malvinas)", "currency_code": "FKP", "currency_name": "Falkland Islands Pound"},
    {"code": "FO", "name": "Faroe Islands", "currency_code": "DKK", "currency_name": "Danish Krone"},
    {"code": "FJ", "name": "Fiji", "currency_code": "FJD", "currency_name": "Fijian Dollar"},
    {"code": "FI", "name": "Finland", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "FR", "name": "France", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "GF", "name": "French Guiana", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "PF", "name": "French Polynesia", "currency_code": "XPF", "currency_name": "CFP Franc"},
    {"code": "TF", "name": "French Southern Territories", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "GA", "name": "Gabon", "currency_code": "XAF", "currency_name": "Central African CFA Franc"},
    {"code": "GM", "name": "Gambia", "currency_code": "GMD", "currency_name": "Gambian Dalasi"},
    {"code": "GE", "name": "Georgia", "currency_code": "GEL", "currency_name": "Georgian Lari"},
    {"code": "DE", "name": "Germany", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "GH", "name": "Ghana", "currency_code": "GHS", "currency_name": "Ghanaian Cedi"},
    {"code": "GI", "name": "Gibraltar", "currency_code": "GIP", "currency_name": "Gibraltar Pound"},
    {"code": "GR", "name": "Greece", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "GL", "name": "Greenland", "currency_code": "DKK", "currency_name": "Danish Krone"},
    {"code": "GD", "name": "Grenada", "currency_code": "XCD", "currency_name": "East Caribbean Dollar"},
    {"code": "GP", "name": "Guadeloupe", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "GU", "name": "Guam", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "GT", "name": "Guatemala", "currency_code": "GTQ", "currency_name": "Guatemalan Quetzal"},
    {"code": "GG", "name": "Guernsey", "currency_code": "GBP", "currency_name": "British Pound"},
    {"code": "GN", "name": "Guinea", "currency_code": "GNF", "currency_name": "Guinean Franc"},
    {"code": "GW", "name": "Guinea-Bissau", "currency_code": "XOF", "currency_name": "West African CFA Franc"},
    {"code": "GY", "name": "Guyana", "currency_code": "GYD", "currency_name": "Guyanese Dollar"},
    {"code": "HT", "name": "Haiti", "currency_code": "HTG", "currency_name": "Haitian Gourde"},
    {"code": "HM", "name": "Heard Island and McDonald Islands", "currency_code": "AUD", "currency_name": "Australian Dollar"},
    {"code": "VA", "name": "Holy See (Vatican City State)", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "HN", "name": "Honduras", "currency_code": "HNL", "currency_name": "Honduran Lempira"},
    {"code": "HK", "name": "Hong Kong", "currency_code": "HKD", "currency_name": "Hong Kong Dollar"},
    {"code": "HU", "name": "Hungary", "currency_code": "HUF", "currency_name": "Hungarian Forint"},
    {"code": "IS", "name": "Iceland", "currency_code": "ISK", "currency_name": "Icelandic Króna"},
    {"code": "IN", "name": "India", "currency_code": "INR", "currency_name": "Indian Rupee"},
    {"code": "ID", "name": "Indonesia", "currency_code": "IDR", "currency_name": "Indonesian Rupiah"},
    {"code": "IR", "name": "Iran, Islamic Republic of", "currency_code": "IRR", "currency_name": "Iranian Rial"},
    {"code": "IQ", "name": "Iraq", "currency_code": "IQD", "currency_name": "Iraqi Dinar"},
    {"code": "IE", "name": "Ireland", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "IM", "name": "Isle of Man", "currency_code": "GBP", "currency_name": "British Pound"},
    {"code": "IL", "name": "Israel", "currency_code": "ILS", "currency_name": "Israeli New Shekel"},
    {"code": "IT", "name": "Italy", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "JM", "name": "Jamaica", "currency_code": "JMD", "currency_name": "Jamaican Dollar"},
    {"code": "JP", "name": "Japan", "currency_code": "JPY", "currency_name": "Japanese Yen"},
    {"code": "JE", "name": "Jersey", "currency_code": "GBP", "currency_name": "British Pound"},
    {"code": "JO", "name": "Jordan", "currency_code": "JOD", "currency_name": "Jordanian Dinar"},
    {"code": "KZ", "name": "Kazakhstan", "currency_code": "KZT", "currency_name": "Kazakhstani Tenge"},
    {"code": "KE", "name": "Kenya", "currency_code": "KES", "currency_name": "Kenyan Shilling"},
    {"code": "KI", "name": "Kiribati", "currency_code": "AUD", "currency_name": "Australian Dollar"},
    {"code": "KP", "name": "Korea, Democratic People's Republic of", "currency_code": "KPW", "currency_name": "North Korean Won"},
    {"code": "KR", "name": "Korea, Republic of", "currency_code": "KRW", "currency_name": "South Korean Won"},
    {"code": "KW", "name": "Kuwait", "currency_code": "KWD", "currency_name": "Kuwaiti Dinar"},
    {"code": "KG", "name": "Kyrgyzstan", "currency_code": "KGS", "currency_name": "Kyrgyzstani Som"},
    {"code": "LA", "name": "Lao People's Democratic Republic", "currency_code": "LAK", "currency_name": "Lao Kip"},
    {"code": "LV", "name": "Latvia", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "LB", "name": "Lebanon", "currency_code": "LBP", "currency_name": "Lebanese Pound"},
    {"code": "LS", "name": "Lesotho", "currency_code": "LSL", "currency_name": "Lesotho Loti"},
    {"code": "LR", "name": "Liberia", "currency_code": "LRD", "currency_name": "Liberian Dollar"},
    {"code": "LY", "name": "Libya", "currency_code": "LYD", "currency_name": "Libyan Dinar"},
    {"code": "LI", "name": "Liechtenstein", "currency_code": "CHF", "currency_name": "Swiss Franc"},
    {"code": "LT", "name": "Lithuania", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "LU", "name": "Luxembourg", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "MO", "name": "Macao", "currency_code": "MOP", "currency_name": "Macanese Pataca"},
    {"code": "MK", "name": "North Macedonia", "currency_code": "MKD", "currency_name": "Macedonian Denar"},
    {"code": "MG", "name": "Madagascar", "currency_code": "MGA", "currency_name": "Malagasy Ariary"},
    {"code": "MW", "name": "Malawi", "currency_code": "MWK", "currency_name": "Malawian Kwacha"},
    {"code": "MY", "name": "Malaysia", "currency_code": "MYR", "currency_name": "Malaysian Ringgit"},
    {"code": "MV", "name": "Maldives", "currency_code": "MVR", "currency_name": "Maldivian Rufiyaa"},
    {"code": "ML", "name": "Mali", "currency_code": "XOF", "currency_name": "West African CFA Franc"},
    {"code": "MT", "name": "Malta", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "MH", "name": "Marshall Islands", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "MQ", "name": "Martinique", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "MR", "name": "Mauritania", "currency_code": "MRU", "currency_name": "Mauritanian Ouguiya"},
    {"code": "MU", "name": "Mauritius", "currency_code": "MUR", "currency_name": "Mauritian Rupee"},
    {"code": "YT", "name": "Mayotte", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "MX", "name": "Mexico", "currency_code": "MXN", "currency_name": "Mexican Peso"},
    {"code": "FM", "name": "Micronesia, Federated States of", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "MD", "name": "Moldova, Republic of", "currency_code": "MDL", "currency_name": "Moldovan Leu"},
    {"code": "MC", "name": "Monaco", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "MN", "name": "Mongolia", "currency_code": "MNT", "currency_name": "Mongolian Tögrög"},
    {"code": "ME", "name": "Montenegro", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "MS", "name": "Montserrat", "currency_code": "XCD", "currency_name": "East Caribbean Dollar"},
    {"code": "MA", "name": "Morocco", "currency_code": "MAD", "currency_name": "Moroccan Dirham"},
    {"code": "MZ", "name": "Mozambique", "currency_code": "MZN", "currency_name": "Mozambican Metical"},
    {"code": "MM", "name": "Myanmar", "currency_code": "MMK", "currency_name": "Burmese Kyat"},
    {"code": "NA", "name": "Namibia", "currency_code": "NAD", "currency_name": "Namibian Dollar"},
    {"code": "NR", "name": "Nauru", "currency_code": "AUD", "currency_name": "Australian Dollar"},
    {"code": "NP", "name": "Nepal", "currency_code": "NPR", "currency_name": "Nepalese Rupee"},
    {"code": "NL", "name": "Netherlands", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "NC", "name": "New Caledonia", "currency_code": "XPF", "currency_name": "CFP Franc"},
    {"code": "NZ", "name": "New Zealand", "currency_code": "NZD", "currency_name": "New Zealand Dollar"},
    {"code": "NI", "name": "Nicaragua", "currency_code": "NIO", "currency_name": "Nicaraguan Córdoba"},
    {"code": "NE", "name": "Niger", "currency_code": "XOF", "currency_name": "West African CFA Franc"},
    {"code": "NG", "name": "Nigeria", "currency_code": "NGN", "currency_name": "Nigerian Naira"},
    {"code": "NU", "name": "Niue", "currency_code": "NZD", "currency_name": "New Zealand Dollar"},
    {"code": "NF", "name": "Norfolk Island", "currency_code": "AUD", "currency_name": "Australian Dollar"},
    {"code": "MP", "name": "Northern Mariana Islands", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "NO", "name": "Norway", "currency_code": "NOK", "currency_name": "Norwegian Krone"},
    {"code": "OM", "name": "Oman", "currency_code": "OMR", "currency_name": "Omani Rial"},
    {"code": "PK", "name": "Pakistan", "currency_code": "PKR", "currency_name": "Pakistani Rupee"},
    {"code": "PW", "name": "Palau", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "PS", "name": "Palestine, State of", "currency_code": "ILS", "currency_name": "Israeli New Shekel"},
    {"code": "PA", "name": "Panama", "currency_code": "PAB", "currency_name": "Panamanian Balboa"},
    {"code": "PG", "name": "Papua New Guinea", "currency_code": "PGK", "currency_name": "Papua New Guinean Kina"},
    {"code": "PY", "name": "Paraguay", "currency_code": "PYG", "currency_name": "Paraguayan Guaraní"},
    {"code": "PE", "name": "Peru", "currency_code": "PEN", "currency_name": "Peruvian Sol"},
    {"code": "PH", "name": "Philippines", "currency_code": "PHP", "currency_name": "Philippine Peso"},
    {"code": "PN", "name": "Pitcairn", "currency_code": "NZD", "currency_name": "New Zealand Dollar"},
    {"code": "PL", "name": "Poland", "currency_code": "PLN", "currency_name": "Polish Zloty"},
    {"code": "PT", "name": "Portugal", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "PR", "name": "Puerto Rico", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "QA", "name": "Qatar", "currency_code": "QAR", "currency_name": "Qatari Riyal"},
    {"code": "RE", "name": "Réunion", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "RO", "name": "Romania", "currency_code": "RON", "currency_name": "Romanian Leu"},
    {"code": "RU", "name": "Russian Federation", "currency_code": "RUB", "currency_name": "Russian Ruble"},
    {"code": "RW", "name": "Rwanda", "currency_code": "RWF", "currency_name": "Rwandan Franc"},
    {"code": "BL", "name": "Saint Barthélemy", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "SH", "name": "Saint Helena, Ascension and Tristan da Cunha", "currency_code": "SHP", "currency_name": "Saint Helena Pound"},
    {"code": "KN", "name": "Saint Kitts and Nevis", "currency_code": "XCD", "currency_name": "East Caribbean Dollar"},
    {"code": "LC", "name": "Saint Lucia", "currency_code": "XCD", "currency_name": "East Caribbean Dollar"},
    {"code": "MF", "name": "Saint Martin (French part)", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "PM", "name": "Saint Pierre and Miquelon", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "VC", "name": "Saint Vincent and the Grenadines", "currency_code": "XCD", "currency_name": "East Caribbean Dollar"},
    {"code": "WS", "name": "Samoa", "currency_code": "WST", "currency_name": "Samoan Tālā"},
    {"code": "SM", "name": "San Marino", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "ST", "name": "Sao Tome and Principe", "currency_code": "STN", "currency_name": "São Tomé and Príncipe Dobra"},
    {"code": "SA", "name": "Saudi Arabia", "currency_code": "SAR", "currency_name": "Saudi Riyal"},
    {"code": "SN", "name": "Senegal", "currency_code": "XOF", "currency_name": "West African CFA Franc"},
    {"code": "RS", "name": "Serbia", "currency_code": "RSD", "currency_name": "Serbian Dinar"},
    {"code": "SC", "name": "Seychelles", "currency_code": "SCR", "currency_name": "Seychellois Rupee"},
    {"code": "SL", "name": "Sierra Leone", "currency_code": "SLL", "currency_name": "Sierra Leonean Leone"},
    {"code": "SG", "name": "Singapore", "currency_code": "SGD", "currency_name": "Singapore Dollar"},
    {"code": "SX", "name": "Sint Maarten (Dutch part)", "currency_code": "ANG", "currency_name": "Netherlands Antillean Guilder"},
    {"code": "SK", "name": "Slovakia", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "SI", "name": "Slovenia", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "SB", "name": "Solomon Islands", "currency_code": "SBD", "currency_name": "Solomon Islands Dollar"},
    {"code": "SO", "name": "Somalia", "currency_code": "SOS", "currency_name": "Somali Shilling"},
    {"code": "ZA", "name": "South Africa", "currency_code": "ZAR", "currency_name": "South African Rand"},
    {"code": "GS", "name": "South Georgia and the South Sandwich Islands", "currency_code": "GBP", "currency_name": "British Pound"},
    {"code": "SS", "name": "South Sudan", "currency_code": "SSP", "currency_name": "South Sudanese Pound"},
    {"code": "ES", "name": "Spain", "currency_code": "EUR", "currency_name": "Euro"},
    {"code": "LK", "name": "Sri Lanka", "currency_code": "LKR", "currency_name": "Sri Lankan Rupee"},
    {"code": "SD", "name": "Sudan", "currency_code": "SDG", "currency_name": "Sudanese Pound"},
    {"code": "SR", "name": "Suriname", "currency_code": "SRD", "currency_name": "Surinamese Dollar"},
    {"code": "SJ", "name": "Svalbard and Jan Mayen", "currency_code": "NOK", "currency_name": "Norwegian Krone"},
    {"code": "SZ", "name": "Eswatini", "currency_code": "SZL", "currency_name": "Swazi Lilangeni"},
    {"code": "SE", "name": "Sweden", "currency_code": "SEK", "currency_name": "Swedish Krona"},
    {"code": "CH", "name": "Switzerland", "currency_code": "CHF", "currency_name": "Swiss Franc"},
    {"code": "SY", "name": "Syrian Arab Republic", "currency_code": "SYP", "currency_name": "Syrian Pound"},
    {"code": "TW", "name": "Taiwan, Province of China", "currency_code": "TWD", "currency_name": "New Taiwan Dollar"},
    {"code": "TJ", "name": "Tajikistan", "currency_code": "TJS", "currency_name": "Tajikistani Somoni"},
    {"code": "TZ", "name": "Tanzania, United Republic of", "currency_code": "TZS", "currency_name": "Tanzanian Shilling"},
    {"code": "TH", "name": "Thailand", "currency_code": "THB", "currency_name": "Thai Baht"},
    {"code": "TL", "name": "Timor-Leste", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "TG", "name": "Togo", "currency_code": "XOF", "currency_name": "West African CFA Franc"},
    {"code": "TK", "name": "Tokelau", "currency_code": "NZD", "currency_name": "New Zealand Dollar"},
    {"code": "TO", "name": "Tonga", "currency_code": "TOP", "currency_name": "Tongan Paʻanga"},
    {"code": "TT", "name": "Trinidad and Tobago", "currency_code": "TTD", "currency_name": "Trinidad and Tobago Dollar"},
    {"code": "TN", "name": "Tunisia", "currency_code": "TND", "currency_name": "Tunisian Dinar"},
    {"code": "TR", "name": "Turkey", "currency_code": "TRY", "currency_name": "Turkish Lira"},
    {"code": "TM", "name": "Turkmenistan", "currency_code": "TMT", "currency_name": "Turkmenistan Manat"},
    {"code": "TC", "name": "Turks and Caicos Islands", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "TV", "name": "Tuvalu", "currency_code": "AUD", "currency_name": "Australian Dollar"},
    {"code": "UG", "name": "Uganda", "currency_code": "UGX", "currency_name": "Ugandan Shilling"},
    {"code": "UA", "name": "Ukraine", "currency_code": "UAH", "currency_name": "Ukrainian Hryvnia"},
    {"code": "AE", "name": "United Arab Emirates", "currency_code": "AED", "currency_name": "UAE Dirham"},
    {"code": "GB", "name": "United Kingdom", "currency_code": "GBP", "currency_name": "British Pound"},
    {"code": "US", "name": "United States", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "UM", "name": "United States Minor Outlying Islands", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "UY", "name": "Uruguay", "currency_code": "UYU", "currency_name": "Uruguayan Peso"},
    {"code": "UZ", "name": "Uzbekistan", "currency_code": "UZS", "currency_name": "Uzbekistani Soʻm"},
    {"code": "VU", "name": "Vanuatu", "currency_code": "VUV", "currency_name": "Vanuatu Vatu"},
    {"code": "VE", "name": "Venezuela, Bolivarian Republic of", "currency_code": "VES", "currency_name": "Venezuelan Bolívar Soberano"},
    {"code": "VN", "name": "Viet Nam", "currency_code": "VND", "currency_name": "Vietnamese Dong"},
    {"code": "VG", "name": "Virgin Islands, British", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "VI", "name": "Virgin Islands, U.S.", "currency_code": "USD", "currency_name": "US Dollar"},
    {"code": "WF", "name": "Wallis and Futuna", "currency_code": "XPF", "currency_name": "CFP Franc"},
    {"code": "EH", "name": "Western Sahara", "currency_code": "MAD", "currency_name": "Moroccan Dirham"},
    {"code": "YE", "name": "Yemen", "currency_code": "YER", "currency_name": "Yemeni Rial"},
    {"code": "ZM", "name": "Zambia", "currency_code": "ZMW", "currency_name": "Zambian Kwacha"},
    {"code": "ZW", "name": "Zimbabwe", "currency_code": "ZWL", "currency_name": "Zimbabwean Dollar"}
]

def seed_countries():
    db = SessionLocal()
    try:
        logger.info("Seeding countries...")
        count = 0
        updated = 0
        for country_data in COUNTRIES:
            existing = db.query(Country).filter(Country.code == country_data["code"]).first()
            if not existing:
                country = Country(**country_data)
                db.add(country)
                count += 1
            else:
                # Update existing
                existing.name = country_data["name"]
                existing.currency_code = country_data["currency_code"]
                existing.currency_name = country_data["currency_name"]
                updated += 1
        
        db.commit()
        logger.info(f"Seeded {count} new countries and updated {updated} existing countries.")
    except Exception as e:
        logger.error(f"Error seeding countries: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    seed_countries()
