"""Add UserInvite model

Revision ID: 4760b8bbc168
Revises: 95a9a05b36a0
Create Date: 2025-12-15 11:46:53.767728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4760b8bbc168'
down_revision: Union[str, None] = '95a9a05b36a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invites',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invites_email'), 'user_invites', ['email'], unique=False)
    op.create_index(op.f('ix_user_invites_token'), 'user_invites', ['token'], unique=True)
    # op.create_index(op.f('ix_user_invites_token'), 'user_invites', ['token'], unique=True)
    # op.alter_column('approval_logs', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('approval_logs', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('approval_logs', 'deleted_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    # op.alter_column('hs_codes', 'approval_status',
    #            existing_type=postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='approvalstatus'),
    #            type_=sa.String(length=20),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'APPROVED'::approvalstatus"))
    # op.drop_index('ix_hs_codes_approval_status', table_name='hs_codes')
    # op.alter_column('manufacturers', 'rejection_reason',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=500),
    #            existing_nullable=True)
    # op.drop_index('ix_manufacturers_approval_status', table_name='manufacturers')
    # op.alter_column('partners', 'type',
    #            existing_type=postgresql.ENUM('supplier', 'customer', 'AR_storage', 'forwarder', name='partner_type_enum'),
    #            type_=sa.Enum('supplier', 'customer', 'AR_storage', 'forwarder', name='partnertypeenum'),
    #            existing_nullable=True)
    # op.drop_index('idx_parts_equivalence_group', table_name='parts')
    # op.create_index(op.f('ix_parts_equivalence_group_id'), 'parts', ['equivalence_group_id'], unique=False)
    # op.alter_column('parts_equivalence', 'part_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # op.alter_column('parts_equivalence', 'equivalent_part_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # op.drop_index('idx_parts_equiv_created_at', table_name='parts_equivalence')
    # op.drop_index('idx_parts_equiv_equiv_id', table_name='parts_equivalence', postgresql_where='(deleted_at IS NULL)')
    # op.drop_index('idx_parts_equiv_part_id', table_name='parts_equivalence', postgresql_where='(deleted_at IS NULL)')
    # op.drop_constraint('uq_parts_equivalence_parts', 'parts_equivalence', type_='unique')
    # op.drop_index('ix_ports_approval_status', table_name='ports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_ports_approval_status', 'ports', ['approval_status'], unique=False)
    # op.create_unique_constraint('uq_parts_equivalence_parts', 'parts_equivalence', ['part_id', 'equivalent_part_id'])
    # op.create_index('idx_parts_equiv_part_id', 'parts_equivalence', ['part_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    # op.create_index('idx_parts_equiv_equiv_id', 'parts_equivalence', ['equivalent_part_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    # op.create_index('idx_parts_equiv_created_at', 'parts_equivalence', ['created_at'], unique=False)
    # op.alter_column('parts_equivalence', 'equivalent_part_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.alter_column('parts_equivalence', 'part_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.drop_index(op.f('ix_parts_equivalence_group_id'), table_name='parts')
    # op.create_index('idx_parts_equivalence_group', 'parts', ['equivalence_group_id'], unique=False)
    # op.alter_column('partners', 'type',
    #            existing_type=sa.Enum('supplier', 'customer', 'AR_storage', 'forwarder', name='partnertypeenum'),
    #            type_=postgresql.ENUM('supplier', 'customer', 'AR_storage', 'forwarder', name='partner_type_enum'),
    #            existing_nullable=True)
    # op.create_index('ix_manufacturers_approval_status', 'manufacturers', ['approval_status'], unique=False)
    # op.alter_column('manufacturers', 'rejection_reason',
    #            existing_type=sa.String(length=500),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.create_index('ix_hs_codes_approval_status', 'hs_codes', ['approval_status'], unique=False)
    # op.alter_column('hs_codes', 'approval_status',
    #            existing_type=sa.String(length=20),
    #            type_=postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='approvalstatus'),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'APPROVED'::approvalstatus"))
    # op.alter_column('approval_logs', 'deleted_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=True)
    # op.alter_column('approval_logs', 'updated_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # op.alter_column('approval_logs', 'created_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    op.drop_index(op.f('ix_user_invites_token'), table_name='user_invites')
    op.drop_index(op.f('ix_user_invites_email'), table_name='user_invites')
    op.drop_table('user_invites')
    # ### end Alembic commands ###
