"""fix_drive_side_enum_conflict

Revision ID: 5cad6a49ba78
Revises: 2cc8cefe48c9
Create Date: 2025-11-25 15:11:40.322964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cad6a49ba78'
down_revision: Union[str, None] = '2cc8cefe48c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'hs_code_tariff', 'hs_codes', ['hs_code'], ['hs_code'])
    op.alter_column('part_translation_standardization', 'drive_side_specific',
               existing_type=postgresql.ENUM('yes', 'no', name='drive_side_enum'),
               type_=sa.Enum('yes', 'no', name='drive_side_specific_enum'),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('part_translation_standardization', 'drive_side_specific',
               existing_type=sa.Enum('yes', 'no', name='drive_side_specific_enum'),
               type_=postgresql.ENUM('yes', 'no', name='drive_side_enum'),
               existing_nullable=True)
    op.drop_constraint(None, 'hs_code_tariff', type_='foreignkey')
    # ### end Alembic commands ###
