"""Add email_sent to UserInvite

Revision ID: 6183f3aa9ba3
Revises: 4760b8bbc168
Create Date: 2025-12-15 12:48:15.495782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6183f3aa9ba3'
down_revision: Union[str, None] = '4760b8bbc168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('approval_logs', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('approval_logs', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('approval_logs', 'deleted_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    # op.alter_column('hs_codes', 'approval_status',
    #            existing_type=postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='approvalstatus'),
    #            type_=sa.String(length=20),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'APPROVED'::approvalstatus"))
    # op.drop_index('ix_hs_codes_approval_status', table_name='hs_codes')
    # op.alter_column('manufacturers', 'rejection_reason',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=500),
    #            existing_nullable=True)
    # op.drop_index('ix_manufacturers_approval_status', table_name='manufacturers')
    # op.alter_column('partners', 'type',
    #            existing_type=postgresql.ENUM('supplier', 'customer', 'AR_storage', 'forwarder', name='partner_type_enum'),
    #            type_=sa.Enum('supplier', 'customer', 'AR_storage', 'forwarder', name='partnertypeenum'),
    #            existing_nullable=True)
    # op.drop_index('idx_parts_equivalence_group', table_name='parts')
    # op.create_index(op.f('ix_parts_equivalence_group_id'), 'parts', ['equivalence_group_id'], unique=False)
    # op.alter_column('parts_equivalence', 'part_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # op.alter_column('parts_equivalence', 'equivalent_part_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # op.drop_index('idx_parts_equiv_created_at', table_name='parts_equivalence')
    # op.drop_index('idx_parts_equiv_equiv_id', table_name='parts_equivalence', postgresql_where='(deleted_at IS NULL)')
    # op.drop_index('idx_parts_equiv_part_id', table_name='parts_equivalence', postgresql_where='(deleted_at IS NULL)')
    # op.drop_constraint('uq_parts_equivalence_parts', 'parts_equivalence', type_='unique')
    # op.drop_index('ix_ports_approval_status', table_name='ports')
    op.add_column('user_invites', sa.Column('email_sent', sa.Boolean(), nullable=True))
    op.add_column('user_invites', sa.Column('email_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_invites', 'email_error')
    op.drop_column('user_invites', 'email_sent')
    # op.create_index('ix_ports_approval_status', 'ports', ['approval_status'], unique=False)
    # op.create_unique_constraint('uq_parts_equivalence_parts', 'parts_equivalence', ['part_id', 'equivalent_part_id'])
    # op.create_index('idx_parts_equiv_part_id', 'parts_equivalence', ['part_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    # op.create_index('idx_parts_equiv_equiv_id', 'parts_equivalence', ['equivalent_part_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    # op.create_index('idx_parts_equiv_created_at', 'parts_equivalence', ['created_at'], unique=False)
    # op.alter_column('parts_equivalence', 'equivalent_part_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.alter_column('parts_equivalence', 'part_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    # op.drop_index(op.f('ix_parts_equivalence_group_id'), table_name='parts')
    # op.create_index('idx_parts_equivalence_group', 'parts', ['equivalence_group_id'], unique=False)
    # op.alter_column('partners', 'type',
    #            existing_type=sa.Enum('supplier', 'customer', 'AR_storage', 'forwarder', name='partnertypeenum'),
    #            type_=postgresql.ENUM('supplier', 'customer', 'AR_storage', 'forwarder', name='partner_type_enum'),
    #            existing_nullable=True)
    # op.create_index('ix_manufacturers_approval_status', 'manufacturers', ['approval_status'], unique=False)
    # op.alter_column('manufacturers', 'rejection_reason',
    #            existing_type=sa.String(length=500),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.create_index('ix_hs_codes_approval_status', 'hs_codes', ['approval_status'], unique=False)
    # op.alter_column('hs_codes', 'approval_status',
    #            existing_type=sa.String(length=20),
    #            type_=postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='approvalstatus'),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'APPROVED'::approvalstatus"))
    # op.alter_column('approval_logs', 'deleted_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=True)
    # op.alter_column('approval_logs', 'updated_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # op.alter_column('approval_logs', 'created_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
