"""add_countries_table_v2

Revision ID: b41f8da918f2
Revises: 5cad6a49ba78
Create Date: 2025-11-27 08:27:09.227479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b41f8da918f2'
down_revision: Union[str, None] = '5cad6a49ba78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('currency_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.drop_table('grns')
    op.drop_index(op.f('idx_fx_rate_currency'), table_name='fx_rate')
    op.drop_table('fx_rate')
    op.drop_index(op.f('idx_freight_costs_shipment'), table_name='freight_costs')
    op.drop_table('freight_costs')
    op.drop_index(op.f('idx_contacts_partner'), table_name='contacts')
    op.alter_column('partners', 'type',
               existing_type=postgresql.ENUM('supplier', 'customer', 'AR_storage', 'forwarder', name='partner_type_enum'),
               type_=sa.Enum('SUPPLIER', 'CUSTOMER', 'AR_STORAGE', 'FORWARDER', name='partnertypeenum'),
               existing_nullable=True)
    op.drop_index(op.f('idx_partners_deleted_at'), table_name='partners')
    op.drop_index(op.f('idx_partners_type'), table_name='partners')
    op.add_column('ports', sa.Column('type', sa.Enum('SEA', 'AIR', 'LAND', name='porttypeenum'), nullable=True))
    op.alter_column('ports', 'port_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('ports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('ports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('ports', 'deleted_at')
    op.drop_column('ports', 'port_type')
    op.drop_constraint(op.f('unique_part_tier'), 'price_tiers_map', type_='unique')
    op.drop_index(op.f('idx_quote_items_quote'), table_name='quote_items')
    op.drop_index(op.f('idx_quotes_status'), table_name='quotes')
    op.drop_index(op.f('idx_supplier_parts_supplier'), table_name='supplier_parts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_supplier_parts_supplier'), 'supplier_parts', ['supplier_id'], unique=False)
    op.create_index(op.f('idx_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_index(op.f('idx_quote_items_quote'), 'quote_items', ['quote_id'], unique=False)
    op.create_unique_constraint(op.f('unique_part_tier'), 'price_tiers_map', ['part_id', 'tier_id'], postgresql_nulls_not_distinct=False)
    op.add_column('ports', sa.Column('port_type', postgresql.ENUM('Sea', 'Air', 'Land', name='port_type_enum'), autoincrement=False, nullable=True))
    op.add_column('ports', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('ports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ports', 'port_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_column('ports', 'type')
    op.create_index(op.f('idx_partners_type'), 'partners', ['type'], unique=False)
    op.create_index(op.f('idx_partners_deleted_at'), 'partners', ['deleted_at'], unique=False)
    op.alter_column('partners', 'type',
               existing_type=sa.Enum('SUPPLIER', 'CUSTOMER', 'AR_STORAGE', 'FORWARDER', name='partnertypeenum'),
               type_=postgresql.ENUM('supplier', 'customer', 'AR_storage', 'forwarder', name='partner_type_enum'),
               existing_nullable=True)
    op.create_index(op.f('idx_contacts_partner'), 'contacts', ['partner_id'], unique=False)
    op.create_table('freight_costs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('shipment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cost_type', postgresql.ENUM('freight', 'insurance', 'other', name='shipment_cost_type_enum'), autoincrement=False, nullable=True),
    sa.Column('cost_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_freight_shipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('freight_costs_pkey'))
    )
    op.create_index(op.f('idx_freight_costs_shipment'), 'freight_costs', ['shipment_id'], unique=False)
    op.create_table('fx_rate',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('fx_rate', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('rate_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fx_rate_pkey')),
    sa.UniqueConstraint('currency_code', 'rate_date', name=op.f('unique_currency_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_fx_rate_currency'), 'fx_rate', ['currency_code', 'rate_date'], unique=False)
    op.create_table('grns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('grn_ref_num', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('quote_ref_num', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('responsible_partner', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('origin_port', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('dest_port', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pickup_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('grns_pkey')),
    sa.UniqueConstraint('grn_ref_num', name=op.f('grns_grn_ref_num_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('countries')
    # ### end Alembic commands ###
