"""add_cascade_update_to_part_name_en

Revision ID: ba939225f746
Revises: 273337e780f7
Create Date: 2025-12-12 18:13:45.921468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba939225f746'
down_revision: Union[str, None] = '273337e780f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parts_part_name_en_fkey', 'parts', type_='foreignkey')
    op.create_foreign_key('parts_part_name_en_fkey', 'parts', 'part_translation_standardization', ['part_name_en'], ['part_name_en'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parts_part_name_en_fkey', 'parts', type_='foreignkey')
    op.create_foreign_key('parts_part_name_en_fkey', 'parts', 'part_translation_standardization', ['part_name_en'], ['part_name_en'])
    # ### end Alembic commands ###
